<?php

$CONFIG = array(
    'STORAGE_DIR' => ROOT_DIR . '/storage',
    'MAKE_STORAGE_DIR' => true,
    'SITE_TITLE' => 'Deaddrop',
    'ATTRIBUTION_HELP' => "Enter in any attribution information that you would like included with your files.",
    'ATTRIBUTION_MAX_LEN' => 1000,
    'ATTRIBUTION_SEPARATOR' => '================================================',
    'ATTRIBUTION_FILENAME' => 'attribution.txt',
    'DROPZONE_PARALLEL_UPLOADS' => 1,
    'DROPZONE_MAX_FILESIZE' => 15,
    'MIME_CUSTOM' => array(),
    'MIME_OVERRIDE_CUSTOM' => array(),

    'MIME_BASE' => array(
        'image/bmp' => '.bmp',
        'image/gif' => '.gif',
        'image/jpeg' => '.jpg',
        'image/jpeg' => '.jpeg',
        'image/png' => '.png',
        'image/svg+xml' => '.svg',
        'image/tiff' => '.tiff',
        'image/vnd.adobe.photoshop' => '.psd',
        'image/x-pcx' => '.pcx',
        'image/x-pict' => '.pic',

        // RAW formats
        'image/x-adobe-dng' => '.dng',
        'image/x-canon-crw' => '.crw',
        'image/x-canon-cr2' => '.cr2',
        'image/x-epson-erf' => '.erf',
        'image/x-fuji-raf' => '.raf',
        'image/x-kodak-dcr' => '.dcr',
        'image/x-kodak-k25' => '.k25',
        'image/x-kodak-kdc' => '.kdc',
        'image/x-minolta-mrw' => '.mrw"',
        'image/x-nikon-nef' => '.nef',
        'image/x-olympus-orf' => '.orf',
        'image/x-panasonic-raw' => '.raw',
        'image/x-pentax-pef' => '.pef',
        'image/x-sigma-x3f' => '.x3f',
        'image/x-sony-srf' => '.srf',
        'image/x-sony-sr2' => '.sr2',
        'image/x-sony-arw' => '.arw',
    ),
    'MIME_OVERRIDE_BASE' => array(
        'image/tiff' => array(
            '.dng' => 'image/x-adobe-dng',
            '.cr2' => 'image/x-canon-cr2',
            '.erf' => 'image/x-epson-erf',
            '.dcr' => 'image/x-kodak-dcr',
            '.k25' => 'image/x-kodak-k25',
            '.kdc' => 'image/x-kodak-kdc',
            '.nef' => 'image/x-nikon-nef',
            '.pef' => 'image/x-pentax-pef',
            '.x3f' => 'image/x-sigma-x3f',
            '.srf' => 'image/x-sony-srf',
            '.sr2' => 'image/x-sony-sr2',
            '.arw' => 'image/x-sony-arw',
        ),
    ),
);
